-- MySQL Script generated by MySQL Workbench
-- Fri Jun 24 14:30:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u825179380_ab2co
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u825179380_ab2co
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u825179380_ab2co` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `u825179380_ab2co` ;

-- -----------------------------------------------------
-- Table `u825179380_ab2co`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u825179380_ab2co`.`Agendamento` (
  `idAgendamento` INT(11) NOT NULL AUTO_INCREMENT,
  `turno` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `dias` INT(11) NOT NULL,
  `entrega` INT(11) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `marmitas` INT(11) NULL DEFAULT NULL,
  `dataPedido` DATETIME NULL DEFAULT NULL,
  `dataEntrega` DATETIME NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idAgendamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u825179380_ab2co`.`Cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u825179380_ab2co`.`Cardapio` (
  `idCardapio` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `dataCriacao` DATETIME NULL DEFAULT NULL,
  `tipo` INT(11) NULL DEFAULT NULL,
  `imagem` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idCardapio`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u825179380_ab2co`.`usuarioCardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u825179380_ab2co`.`usuarioCardapio` (
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `perfil` INT(11) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(11) NOT NULL,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `u825179380_ab2co`.`sacola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u825179380_ab2co`.`sacola` (
  `idAgendamento` INT(11) NOT NULL,
  `idCardapio` INT(11) NOT NULL,
  `cpfUsuario` VARCHAR(11) NOT NULL,
  `tipo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idAgendamento`, `idCardapio`, `cpfUsuario`),
  INDEX `fk_idCardapio_idx` (`idCardapio` ASC),
  INDEX `fk_CPF_usuario` (`cpfUsuario` ASC),
  CONSTRAINT `fk_CPF_usuario`
    FOREIGN KEY (`cpfUsuario`)
    REFERENCES `u825179380_ab2co`.`usuarioCardapio` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idAgendamento`
    FOREIGN KEY (`idAgendamento`)
    REFERENCES `u825179380_ab2co`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCardapio`
    FOREIGN KEY (`idCardapio`)
    REFERENCES `u825179380_ab2co`.`Cardapio` (`idCardapio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
